config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get 'simple_pages/landing_page'
  root 'simple_pages#landing_page'

  post 'simple_pages/thank_you'
  post 'payments/create'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueerBroadsAbroad</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <script src="https://use.fontawesome.com/09c9551280.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.js" integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <% if notice %>
      <p id="notice" class="alert alert-primary" role="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-warning" role="alert"><%= alert %></p>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">QueerBroadsAbroad</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-item nav-link active"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link"><%= link_to "About", simple_pages_about_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link"><%= link_to "Contact", simple_pages_contact_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link"><%= link_to "Products", products_path %></a>
          </li>
        </ul>
        <div class="search-nav navbar-left">
          <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
          <%= form.text_field :q, id: 'q', value: params[:q], class: "search-field", placeholder: "Search here" %>
          <%= form.submit 'Search', class: 'search-button' %>
          <% end %>
        </div><!--end search div-->
        <div class="login-logout">
          <ul class="navbar-nav ml-auto navbar-right">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_user_session_path, class: "nav-link") %>
            </li>
            <% end %>
          </ul>
        </div><!--end login-->
      </div>
    </nav>
    <%= yield %>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">&copy; 2018 Gipsy Redman</span>
      </div>
    </footer>
  </body>
</html>